<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * BattleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleRepository extends EntityRepository
{
    public function findAllClanBattles( $clanTag )
    {
        $query = $this->createQueryBuilder('b')
            ->select(['b.id as DT_RowId',
                        'b.datePlayed',
                        'b.result',
                        'c.username as commander',
                        'b.enemyClan',
                        'b.mapName',
                        'b.stronghold'
            ])
            ->join('b.commander', 'c')
            ->where('b.clan = :clan')
            ->setParameter('clan', $clanTag)
            ->orderBy('b.datePlayed', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
