<?php

namespace AppBundle\Repository;

/**
 * BattleAttendance
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BattleAttendanceRepository extends \Doctrine\ORM\EntityRepository
{
}
