<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventAccountDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventAccountDataRepository extends EntityRepository
{

    /**
     * @param integer $clan_id
     * @param string $event_id
     * @return mixed
     */
    public function deleteClanEventData($clan_id, $event_id)
    {
        $query = $this->getEntityManager()
            ->createQuery(
            'DELETE AppBundle:EventAccountData u
            WHERE u.clan = :clan
            AND u.event = :event')
            ->setParameter("clan", $clan_id)
            ->setParameter("event", $event_id);

        return $query->execute();
    }


}
