<?php
/**
 * Copyright (c) 2016. by vonLeeb_pl@PSQD, MIT License
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PayoutRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class PayoutRepository extends EntityRepository
{
}
