<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * Player
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllByAccountIdsArray(array $arr)
    {
        $query = $this->createQueryBuilder('p')
            ->andWhere('p.accountId IN (:ids)')
            ->setParameter('ids', $arr)
            ->getQuery();

        return $query->getResult();
    }

    public function findAllClanMembersBetweenMinAndExtraResourceEarned( $clan, $minRes, $extraRes  )
    {
        $query = $this->createQueryBuilder('p')
            ->andWhere('p.clan = (:clan)')
            ->andWhere('p.resourcesToPayout >= :minRes')
            ->andWhere('p.resourcesToPayout < :extraRes')
            ->setParameters(['clan' => $clan, 'minRes' => $minRes, 'extraRes' => $extraRes])
            ->getQuery();

        return $query->getResult();
    }

    public function findAllClanMembersWithExtraResourceEarned( $clan, $extraRes  )
    {
        $query = $this->createQueryBuilder('p')
            ->andWhere('p.clan = (:clan)')
            ->andWhere('p.resourcesToPayout >= :extraRes')
            ->setParameters(['clan' => $clan, 'extraRes' => $extraRes])
            ->getQuery();

        return $query->getResult();
    }
}
