<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * Player
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findAllByAccountIdsArray(array $arr)
    {
        $query = $this->createQueryBuilder('p')
            ->andWhere('p.accountId IN (:ids)')
            ->setParameter('ids', $arr)
            ->getQuery();

        return $query->getResult();
    }
}
