<?php

namespace AppBundle\Repository;

/**
 * RefreshMonitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefreshMonitorRepository extends \Doctrine\ORM\EntityRepository
{
}
