<?php

namespace AppBundle\Repository;

/**
 * TankRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TankRepository extends \Doctrine\ORM\EntityRepository
{
}
