imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    security_settings:
        authorised_clans:
            - 'PSQD'
        roles_matrix:
            'ROLE_SOLDIER': ['recruit', 'private', 'reservist', 'junior_officer', 'personnel_officer', 'combat_officer', 'recruitment_officer', 'intelligence_officer']
            'ROLE_OFFICER': ['quartermaster']
            'ROLE_EXECUTIVE_OFFICER': ['executive_officer']
            'ROLE_COMMANDER': ['commander']
        super_admins:
            - 'vonLeeb_pl'
    valid_openid_providers:
        - { name: 'Wargaming EU', url: https://eu.wargaming.net/id/ }


framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
      - 'bootstrap_3_horizontal_layout.html.twig'
      - 'form/fields.html.twig'
    globals:
      valid_openid_providers: "%valid_openid_providers%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            datetime: AppBundle\DoctrineExtensions\DBAL\Types\UTCDateTimeType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Uploader bundle params
vich_uploader:
    db_driver: orm

    mappings:
        replay_file:
            uri_prefix:         /replays
            upload_destination: "%kernel.root_dir%/../web/replays"
            namer:              vich_uploader.namer_origname
# fp_openid_bundle
fp_open_id:
    db_driver: orm
    identity_class: AppBundle\Entity\OpenIdIdentity

# fos_user bundle
#fos_user:
#    db_driver: orm
#    firewall_name: main
#    use_listener: false
#    user_class: AppBundcle\Entity\Player
#    service:
#      user_manager: fp_openid.user_manager

# Stof/Gedmo Doctrine Extensions config
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sortable: true